version: "3.2"
services:
  mysqldb:
    image: mysql:5.7
    networks:
      - backend
    environment:
      MYSQL_DATABASE: moviesDb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - 3306
    container_name: mysql-app
  nodejs:
    build: 
      context: .
    image: jhaanshul123/bookmyshow-dummy
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mysql-app
      - MYSQL_PORT=3306
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=moviesDb
    ports:
      - "6001:6001"
    container_name: nodejs-app
    depends_on:
      - mysqldb
networks:
  frontend:
  backend: